In [1]:
import pandas as pd

In [7]:
data = pd.read_csv("student_data.csv")
data

    StudentID    Name  Gender   Age  Department  Marks  Attendance        City
0           1    Amit    Male  20.0    Computer   78.0        85.0        Pune
1           2   Priya  Female  21.0          IT   88.0        90.0      Mumbai
2           3   Rahul    Male  19.0  Mechanical   67.0        75.0      Nashik
3           4   Sneha  Female  22.0    Computer   92.0        95.0        Pune
4           5   Akash    Male  20.0       Civil   55.0        60.0  Aurangabad
5           6    Neha  Female  21.0          IT   73.0        80.0      Mumbai
6           7   Rohan    Male  23.0  Mechanical   49.0        65.0      Nagpur
7           8   Kajal  Female  20.0    Computer   81.0        88.0        Pune
8           9   Arjun    Male  22.0       Civil   60.0        70.0      Nashik
9          10   Pooja  Female  19.0          IT   77.0        85.0      Mumbai
10         11   Vikas    Male   NaN    Computer   85.0        90.0        Pune
11         12  Anjali  Female  21.0         NaN   91.0        92.0      Nagpur
12         13   Karan    Male  20.0       Civil    NaN        78.0  Aurangabad
13         14   Meena  Female  22.0  Mechanical   69.0         NaN      Nashik
14         15  Deepak    Male  21.0          IT   74.0        82.0         NaN

In [8]:
data.describe()

       StudentID        Age      Marks  Attendance
count  15.000000  14.000000  14.000000   14.000000
mean    8.000000  20.785714  74.214286   81.071429
std     4.472136   1.188313  13.186115   10.469474
min     1.000000  19.000000  49.000000   60.000000
25%     4.500000  20.000000  67.500000   75.750000
50%     8.000000  21.000000  75.500000   83.500000
75%    11.500000  21.750000  84.000000   89.500000
max    15.000000  23.000000  92.000000   95.000000

In [10]:
data["Marks"].mean()

np.float64(74.21428571428571)

In [11]:
data["Age"].median()

np.float64(21.0)

In [16]:
data["Marks"].std()

np.float64(13.186114908252026)

In [20]:
data["Attendance"].mode()

0    85.0
1    90.0
Name: Attendance, dtype: float64

In [21]:
df = pd.read_csv("iris.csv")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [22]:
df["species"].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [23]:
df["sepal_length"].describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: sepal_length, dtype: float64

In [30]:
#setosa = df[df["setosa"] == "setosa"]
#print("Setosa: \n", setosa.describe())
df["species"].describe()

count        150
unique         3
top       setosa
freq          50
Name: species, dtype: object

In [31]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

In [33]:
setosa = df[df["species"] == "setosa"]
print("Species: \n", setosa.describe())

Species:
        sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000     50.00000
mean        5.00600     3.418000      1.464000      0.24400
std         0.35249     0.381024      0.173511      0.10721
min         4.30000     2.300000      1.000000      0.10000
25%         4.80000     3.125000      1.400000      0.20000
50%         5.00000     3.400000      1.500000      0.20000
75%         5.20000     3.675000      1.575000      0.30000
max         5.80000     4.400000      1.900000      0.60000

In [34]:
versicolor = df[df["species"] == "versicolor"]
print("Versicolor: \n", versicolor.describe())

Versicolor:
        sepal_length  sepal_width  petal_length  petal_width
count     50.000000    50.000000     50.000000    50.000000
mean       5.936000     2.770000      4.260000     1.326000
std        0.516171     0.313798      0.469911     0.197753
min        4.900000     2.000000      3.000000     1.000000
25%        5.600000     2.525000      4.000000     1.200000
50%        5.900000     2.800000      4.350000     1.300000
75%        6.300000     3.000000      4.600000     1.500000
max        7.000000     3.400000      5.100000     1.800000

In [39]:
virginica = df[df["species"] == "virginica"]
print("Virginica: \n", virginica.describe())

Virginica:
        sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000     50.00000
mean        6.58800     2.974000      5.552000      2.02600
std         0.63588     0.322497      0.551895      0.27465
min         4.90000     2.200000      4.500000      1.40000
25%         6.22500     2.800000      5.100000      1.80000
50%         6.50000     3.000000      5.550000      2.00000
75%         6.90000     3.175000      5.875000      2.30000
max         7.90000     3.800000      6.900000      2.50000